logo:
  path: 'themes/custom/robotic/logo.png'
  use_default: false

#features:
#  comment_user_picture: true
#  comment_user_verification: true
#  favicon: true
#  logo: true
#  name: true
#  node_user_picture: true
#  slogan: true
